# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WinGetGui(object):
    def setupUi(self, WinGetGui):
        WinGetGui.setObjectName("WinGetGui")
        WinGetGui.resize(1033, 653)
        self.centralwidget = QtWidgets.QWidget(WinGetGui)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 430, 1001, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1001, 411))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 560, 1001, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_refresh = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_refresh.setObjectName("pb_refresh")
        self.horizontalLayout.addWidget(self.pb_refresh)
        self.pb_update = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_update.setObjectName("pb_update")
        self.horizontalLayout.addWidget(self.pb_update)
        self.pb_remove = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_remove.setObjectName("pb_remove")
        self.horizontalLayout.addWidget(self.pb_remove)
        self.pb_add_to_ignore = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_add_to_ignore.setObjectName("pb_add_to_ignore")
        self.horizontalLayout.addWidget(self.pb_add_to_ignore)
        WinGetGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WinGetGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 27))
        self.menubar.setObjectName("menubar")
        WinGetGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WinGetGui)
        self.statusbar.setObjectName("statusbar")
        WinGetGui.setStatusBar(self.statusbar)

        self.retranslateUi(WinGetGui)
        QtCore.QMetaObject.connectSlotsByName(WinGetGui)

    def retranslateUi(self, WinGetGui):
        _translate = QtCore.QCoreApplication.translate
        WinGetGui.setWindowTitle(_translate("WinGetGui", "WinGetGui"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("WinGetGui", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("WinGetGui", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("WinGetGui", "Version"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("WinGetGui", "Latest"))
        self.pb_refresh.setText(_translate("WinGetGui", "Refresh"))
        self.pb_update.setText(_translate("WinGetGui", "Update Selected"))
        self.pb_remove.setText(_translate("WinGetGui", "Remove Selected"))
        self.pb_add_to_ignore.setText(_translate("WinGetGui", "Add to ignore list"))
